language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - nightly
    - pypy
    - pypy3

install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* || $TRAVIS_PYTHON_VERSION == 'pypy'*]]; then travis_retry pip install enum34; fi
    - travis_retry pip install -e .
    - travis_retry pip install pytest-cov
    - travis_retry pip install pytest-travis-fold
    - travis_retry python setup.py install
    - curl-config --version; pip freeze

script:
    - py.test
    - LANG=C py.test
    - LANG=en_US.utf-8 py.test
    - py.test --cov=src
    - python run.py --version
    - LANG=C python run.py --version
    - LANG=en_US.utf-8 python run.py --version

sudo: false

matrix:
    fast_finish: true